
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 09 14:18:44 CST 2020
//----------------------------------------------------

package gramaticas;

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int PUNTO = 11;
  public static final int CARPETA = 6;
  public static final int ARCHIVO = 5;
  public static final int PROYECTO = 4;
  public static final int FIN = 16;
  public static final int EOF = 0;
  public static final int NUMERO = 15;
  public static final int MENOR_QUE = 3;
  public static final int PALABRA = 14;
  public static final int DIAGONAL = 12;
  public static final int MAYOR = 2;
  public static final int IGUAL = 9;
  public static final int error = 1;
  public static final int NOMBRE = 7;
  public static final int PATH = 13;
  public static final int COMILLA = 10;
  public static final int UBICACION = 8;
}

