
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 16 18:24:06 CST 2020
//----------------------------------------------------

package gramaticas;

/** CUP generated class containing symbol constants. */
public class sym3 {
  /* terminals */
  public static final int COMA = 2;
  public static final int DATO_NUMERICO = 6;
  public static final int DATO_ALFANUMERICO = 5;
  public static final int error = 1;
  public static final int COMA_ENTER = 4;
  public static final int ENTER = 3;
  public static final int EOF = 0;
  public static final int DATO_DECIMAL = 7;
}

