
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 16 18:24:04 CST 2020
//----------------------------------------------------

package gramaticas;

/** CUP generated class containing symbol constants. */
public class sym4 {
  /* terminals */
  public static final int AND = 11;
  public static final int PUNTO = 26;
  public static final int INSERTAR = 5;
  public static final int IGUAL = 19;
  public static final int OR = 12;
  public static final int MENOR_IGUAL = 22;
  public static final int PALABRA = 25;
  public static final int ELIMINAR = 8;
  public static final int MAYOR_MENOR = 24;
  public static final int MAYOR_IGUAL = 23;
  public static final int MAYOR_QUE = 21;
  public static final int AGRUPACION_B = 16;
  public static final int FILTRAR = 4;
  public static final int AGRUPACION_A = 13;
  public static final int VALORES = 10;
  public static final int ASIGNAR = 7;
  public static final int ACTUALIZAR = 6;
  public static final int COMA = 15;
  public static final int MENOR_QUE = 20;
  public static final int ASTERISCO = 18;
  public static final int EOF = 0;
  public static final int COMILLA = 14;
  public static final int NUMERO = 27;
  public static final int error = 1;
  public static final int PUNTO_COMA = 17;
  public static final int EN = 9;
  public static final int FIN = 3;
  public static final int SELECCIONAR = 2;
}

