package paneles;
import com.sun.glass.events.KeyEvent;
import gramaticas.AnalizadorLexico3;
import gramaticas.AnalizadorLexico4;
import gramaticas.SintacticoPersonal;
import gramaticas.SintaxCSV;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import operacionMysql.OperacionActualizar;
import operacionMysql.OperacionEliminar;
import operacionMysql.OperacionInsertar;
import operacionMysql.OperacionSeleccionar;
import pollitos.DatosColumna;
import pollitos.Filtros;
import pollitos.PolloCSV;
import pollitos.Sentencias;
import pollitos.ValoresInsercion;

/**
 *
 * @author luisGonzalez
 */
public class PanelModelo extends javax.swing.JPanel {

    ArrayList<PolloCSV> list = new ArrayList<>();
    private OperacionSeleccionar seleccion;
    private OperacionInsertar insercion;
    private OperacionActualizar actualizacion;
    private OperacionEliminar eliminacion;
    String path;
    
    
    /**
     * Creates new form PanelModelo
     * @param texto
     * @param path
     */
    public PanelModelo(String texto, String path) {
        initComponents();
        this.path = path;
        panelTexto.setText(texto);
        AnalizadorLexico3 lexico = new AnalizadorLexico3(new StringReader(texto));
        try {
            new SintaxCSV(lexico, list).parse();
            System.out.println("Todo funcionando a la perfeccion");
        } catch (Exception ex) {
            System.out.println("Ha ocurrido un error D:");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelTexto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelConsultas = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelResultados = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        panelHistorial = new javax.swing.JTextArea();

        panelTexto.setColumns(20);
        panelTexto.setRows(5);
        jScrollPane1.setViewportView(panelTexto);

        panelConsultas.setColumns(20);
        panelConsultas.setRows(5);
        panelConsultas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelConsultasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(panelConsultas);

        panelResultados.setColumns(20);
        panelResultados.setRows(5);
        jScrollPane3.setViewportView(panelResultados);

        panelHistorial.setColumns(20);
        panelHistorial.setRows(5);
        jScrollPane4.setViewportView(panelHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void panelConsultasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelConsultasKeyPressed
        String texto = panelConsultas.getText();
        String historial = panelHistorial.getText();
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          if(texto.endsWith(";")){
              analizador();
              if(historial.equals("")){
                  String modificado = panelConsultas.getText().replaceAll("\n", "");
                  panelHistorial.setText(modificado);
              } else {
                  String modificado = panelConsultas.getText().replaceAll("\n", "");
                  panelHistorial.setText(historial + "\n" + modificado);
              }
              panelConsultas.setText("");
          }
        }
    }//GEN-LAST:event_panelConsultasKeyPressed

    private void analizador(){
        String texto = panelConsultas.getText();
        seleccion = new OperacionSeleccionar();
        insercion = new OperacionInsertar();
        actualizacion = new OperacionActualizar();
        eliminacion = new OperacionEliminar();
        AnalizadorLexico4 lexico = new AnalizadorLexico4(new StringReader(texto));
            ArrayList<DatosColumna> listadoColumnas = new ArrayList<>();
            ArrayList<Filtros> listadoFiltro = new ArrayList<>();
            ArrayList<String> opcion = new ArrayList<>();
            ArrayList<Integer> opcionesPrincipales = new ArrayList<>();
            ArrayList<ValoresInsercion> listadoValores = new ArrayList<>();
            ArrayList<Sentencias> listadoNuevosDatos = new ArrayList<>();
            int accionPosible = 0;
        try {
            new SintacticoPersonal(lexico, list, listadoColumnas, listadoFiltro, opcion, opcionesPrincipales, listadoValores, listadoNuevosDatos).parse();
        } catch (Exception ex) {
            Logger.getLogger(PanelModelo.class.getName()).log(Level.SEVERE, null, ex);
        }
            panelResultados.setText("Analisis realizado correctamente");
            if(null != opcionesPrincipales.get(0))
                switch (opcionesPrincipales.get(0)) {
            case 1:
                seleccion.comprobacionColumna(panelResultados, list, listadoColumnas, listadoFiltro, opcion);
                break;
            case 2:
                insercion.insercionDatos(panelResultados, list, listadoColumnas, listadoValores, path, panelTexto);
                break;
            case 3:
                actualizacion.actualizacionDato(panelResultados, listadoNuevosDatos, listadoFiltro, list, path, panelTexto);
                break;
            case 4:
                eliminacion.eliminacionFilas(list, listadoFiltro, panelResultados, panelTexto, path);
                break;
            default:
                break;
        }
            
            
            
            
            
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea panelConsultas;
    private javax.swing.JTextArea panelHistorial;
    private javax.swing.JTextArea panelResultados;
    private javax.swing.JTextArea panelTexto;
    // End of variables declaration//GEN-END:variables
}
